# Inspired from https://github.com/actions/starter-workflows/blob/main/pages/nextjs.yml
name: GitHub Pages

on:
  push:
    branches: main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Capture Start Time
        id: start-time
        run: echo "timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - id: configurepages
        uses: actions/configure-pages@v5
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - run: npm install
      - run: npm run build
        env:
          EXPORT: 1
          UNOPTIMIZED: 1
          BASE_PATH: ${{ steps.configurepages.outputs.base_path }}
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: Send Build Status to Teams
        if: failure() || success() # Run if the job fails or succeeds
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
            "text": "**🔹 CI/CD Status Update 🔹**\n
            📌 *Repository:* ${{ github.repository }}\n
            🔄 *Branch:* ${{ github.ref }}\n
            ✅ *Status:* ${{ job.status }}\n
            🕒 *Timestamp:* ${{ env.timestamp }}\n
            📎 *Build Log:* [View Here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          }' "https://questps.webhook.office.com/webhookb2/d80f341c-dd92-4865-848f-7a1420c5284d@94797e0d-39d7-4f03-9ec2-bc29b56fe1ac/IncomingWebhook/95057c5e8ce6430a840af06d06a6f792/7a16d4ee-67e4-452f-b0c8-6bd88338bd22/V2pGGkN2KMdHbJB-4g2DRkpe0JKDK5wQn2T-4cW40vy3c1"

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
